# Generated by Django 5.0.3 on 2024-03-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cart_code_cartproduct_code_category_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterproduct',
            name='product_name',
        ),
        migrations.AddField(
            model_name='enterproduct',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
