# Generated by Django 5.0.3 on 2024-03-20 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_enterproduct_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterproduct',
            name='code',
        ),
    ]
