# Generated by Django 5.0.3 on 2024-03-20 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_enterproduct_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterproduct',
            name='slug',
        ),
    ]
