# Generated by Django 5.0.3 on 2024-03-20 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_enterproduct_code_enterproduct_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterproduct',
            name='code',
        ),
    ]
