# Generated by Django 5.0.3 on 2024-03-20 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_enterproduct_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
