# Generated by Django 5.0.3 on 2024-03-20 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterproduct',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='enterproduct',
            name='product',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
            preserve_default=False,
        ),
    ]
