# Generated by Django 5.0.3 on 2024-03-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_enterproduct_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='code',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='code',
        ),
        migrations.RemoveField(
            model_name='category',
            name='code',
        ),
        migrations.RemoveField(
            model_name='enterproduct',
            name='code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='code',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='code',
        ),
        migrations.RemoveField(
            model_name='serveorder',
            name='code',
        ),
    ]
