# Generated by Django 5.0.3 on 2024-03-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_cartproduct_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnterProduct',
        ),
    ]
